### ISSUE TITLE
[ENHANCEMENT] OptiGui reports loading every file in resource pack with support

### ISSUE THREAD

**Issue by MeeniMc** [opekope2/OptiGUI#66]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

OptiGUI loads the files without polluting the game log.

### Actual Behavior

OptiGui loads the files, but issues a message for every one file in the game log, that can be a significant number of lines. 

### Steps To Reproduce

Use resource pack `colourful-containers-dark-mode-e1442.zip`

```
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/chests/chest.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/chests/ender.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/dropper/dispenser.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/shulker_box/black.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/shulker_box/blue.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/shulker_box/brown.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/shulker_box/cyan.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/shulker_box/gray.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/shulker_box/green.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/shulker_box/light_blue.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/shulker_box/light_gray.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/shulker_box/lime.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/shulker_box/magenta.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/shulker_box/orange.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/shulker_box/pink.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/shulker_box/purple.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/shulker_box/red.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/shulker_box/white.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/shulker_box/yellow.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/villager/armorer/armorer_1.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/villager/armorer/armorer_2.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/villager/armorer/armorer_3.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/villager/armorer/armorer_4.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/villager/armorer/armorer_5.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/villager/butcher/butcher_1.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/villager/butcher/butcher_2.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/villager/butcher/butcher_3.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/villager/butcher/butcher_4.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/villager/butcher/butcher_5.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/villager/cartographer/cartographer_1.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/villager/cartographer/cartographer_2.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/villager/cartographer/cartographer_3.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/villager/cartographer/cartographer_4.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/villager/cartographer/cartographer_5.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/villager/cleric/cleric_1.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/villager/cleric/cleric_2.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/villager/cleric/cleric_3.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/villager/cleric/cleric_4.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/villager/cleric/cleric_5.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/villager/farmer/farmer_1.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/villager/farmer/farmer_2.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/villager/farmer/farmer_3.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/villager/farmer/farmer_4.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/villager/farmer/farmer_5.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/villager/fisherman/fisherman_1.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/villager/fisherman/fisherman_2.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/villager/fisherman/fisherman_3.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/villager/fisherman/fisherman_4.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/villager/fisherman/fisherman_5.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/villager/fletcher/fletcher_1.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/villager/fletcher/fletcher_2.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/villager/fletcher/fletcher_3.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/villager/fletcher/fletcher_4.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/villager/fletcher/fletcher_5.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/villager/leatherworker/leatherworker_1.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/villager/leatherworker/leatherworker_2.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/villager/leatherworker/leatherworker_3.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/villager/leatherworker/leatherworker_4.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/villager/leatherworker/leatherworker_5.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/villager/librarian/librarian_1.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/villager/librarian/librarian_2.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/villager/librarian/librarian_3.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/villager/librarian/librarian_4.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/villager/librarian/librarian_5.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/villager/mason/mason_1.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/villager/mason/mason_2.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/villager/mason/mason_3.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/villager/mason/mason_4.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/villager/mason/mason_5.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/villager/shepherd/shepherd_1.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/villager/shepherd/shepherd_2.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/villager/shepherd/shepherd_3.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/villager/shepherd/shepherd_4.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/villager/shepherd/shepherd_5.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/villager/toolsmith/toolsmith_1.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/villager/toolsmith/toolsmith_2.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/villager/toolsmith/toolsmith_3.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/villager/toolsmith/toolsmith_4.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/villager/toolsmith/toolsmith_5.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/villager/weaponsmith/weaponsmith_1.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/villager/weaponsmith/weaponsmith_2.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/villager/weaponsmith/weaponsmith_3.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/villager/weaponsmith/weaponsmith_4.properties from file/colourful-containers-dark-mode-e1442.zip
[21:11:51] [Render thread/INFO] (OptiGUI) Loading minecraft:optifine/gui/container/villager/weaponsmith/weaponsmith_5.properties from file/colourful-containers-dark-mode-e1442.zip
```

### Loader and its version

Mc 1.20.1 Fabric 0.14.12

### OptiGUI version

Optigui 2.1.5

### Behavior difference

- [ ] Behavior is different from OptiGUI documentation
- [ ] Behavior is different from OptiFine
- [ ] Behavior is different from expected (or straight up doesn't work)

**Comment by opekope2** [comment]
Well
The logging code is not (yet) in the rewritten code
It was useful for testing and may be useful for resource pack creator
Thanks for the feedback, if I add logging, I'll put it to the debug channel (turned off by default)
You can configure Log4J to disable OptiGUI info logging

**Comment by opekope2** [comment]
I have released OptiGUI 2.2.0-alpha.1, which only logs warnings, if a resource is malformed

**Comment by MeeniMc** [comment]
I think you forgot to embed your lilac library in the published jar.

**Comment by opekope2** [comment]
I'm no longer embedding it. It is a separate project now. It is marked as required in `fabric.mod.json`
